// Offline code generator (run once, and again when the URDF changes).
//
// For each arm, Pinocchio evaluates the joint-space model with the CppADCodeGen scalar (model_ad.cpp)
// and control-toolbox (ct::core::DerivativesCppadCG::generateForwardZeroSource) writes plain C++:
//   input  x = [q (7); dq (7)]
//   output y = [M row-major (49); C row-major (49); G (7)]   (C: Coriolis matrix, C(q, dq) dq)
// The generated classes need only Eigen and ct_core; Pinocchio is not needed at run time.
//
//   generate_model <official urdf> <output dir>
#include "model_ad.hpp"

#include <ct/core/core.h>

#include <fstream>
#include <iomanip>
#include <iostream>

using openarm_codegen::kIn;
using openarm_codegen::kOut;
using Generator = ct::core::DerivativesCppadCG<kIn, kOut>;

int main(int argc, char ** argv)
{
  if (argc != 3) {
    std::cerr << "usage: generate_model <official urdf> <output dir>\n";
    return 2;
  }
  openarm_codegen::loadModel(argv[1]);
  for (const std::string arm : {"right", "left"}) {
    Generator::FUN_TYPE_CG f = [arm](const Generator::IN_TYPE_CG & x) {
        std::vector<openarm_codegen::ADCG> in(x.data(), x.data() + kIn);
        const auto out = openarm_codegen::modelTerms(arm, in);
        Generator::OUT_TYPE_CG y;
        for (int k = 0; k < kOut; ++k) {y(k) = out[k];}
        return y;
      };
    Generator generator(f);
    const std::string name = std::string("OpenArm") + (arm == "right" ? "Right" : "Left") + "Model";
    generator.generateForwardZeroSource(name, argv[2], ct::core::CODEGEN_TEMPLATE_DIR, "openarm", "generated");
    std::cout << "generated " << argv[2] << "/" << name << ".{h,cpp}\n";
  }
  // Joint position limits from the same URDF, for the runtime library.
  std::ofstream limits(std::string(argv[2]) + "/OpenArmLimits.h");
  limits << "// Generated by openarm_codegen/generate_model from the official URDF. Do not edit.\n"
         << "#pragma once\n\nnamespace ct {\nnamespace openarm {\nnamespace generated {\n\n"
         << std::setprecision(17);
  for (const std::string arm : {"right", "left"}) {
    for (const bool upper : {false, true}) {
      limits << "inline constexpr double k" << (arm == "right" ? "Right" : "Left") << (upper ? "Upper" : "Lower")
             << "[7] = {";
      const auto v = openarm_codegen::positionLimits(arm, upper);
      for (size_t j = 0; j < v.size(); ++j) {limits << (j ? ", " : "") << v[j];}
      limits << "};\n";
    }
  }
  limits << "\n}  // namespace generated\n}  // namespace openarm\n}  // namespace ct\n";
  std::cout << "generated " << argv[2] << "/OpenArmLimits.h\n";
  return 0;
}
